repair CLI/context diff execution, mirror editor properties, and fix encoding lookups
fixed on_cli, currently it was not working, now we open the files first then compare them.
and added on_cli to install inf as lazy, and added a config setting to make on_cli not lazy by puting it in plugins.ini if this new setting is set to true like we did with on_start2, so the plugin will auto load when cudatext starts always so compare will always work if the user pass cli commands to do a diff

fixed also "Open with..." and compare_with, currently it was not working, now we open the files first then compare them.

___
when we run a compare currently we copy only PROP_LEXER_FILE, now we copy everything important for a correct compare, line ending PROP_NEWLINE,encoding PROP_ENC, and  PROP_TAB_SPACES and PROP_TAB_SIZE , and PROP_WRAP

___
when i click command diff_with and the current tab use some encodings like koi8u or utf16le i get this error
Traceback (most recent call last):
  File "F:\_bin\_binz\_ide\_CudaText\_last64\py\cuda_differ\__init__.py", line 392, in diff_with
    b = Path(fn).read_text(enc)
  File "pathlib.py", line 1236, in read_text
  File "pathlib.py", line 1222, in open
LookupError: unknown encoding: utf16le
ERROR: Exception in CudaText for diff_with: LookupError: unknown encoding: utf16le

the plugin attempted to pass the cudatext encoding name to python

___

in readme.txt in "Available options include" section added the config names too ,and document all settings

gap_color had no default color, now we use LightBG5 like we do with changed_color/added_color