fix IndexError error when compared tab is empty - improve ui - reapply colors when cuda start
when i compare two empty tabs i get error:
Traceback (most recent call last):
  File "F:\_bin\_binz\_ide\_CudaText\_last64\py\cuda_differ\__init__.py", line 324, in diff_with_tab
    self.create_diff(a, b, name0, name)
  File "F:\_bin\_binz\_ide\_CudaText\_last64\py\cuda_differ\__init__.py", line 419, in create_diff
    if txt0[-1] != '\n': txt0 += '\n'
IndexError: string index out of range
ERROR: Exception in CudaText for diff_with_tab: IndexError: string index out of range

replace on_change with on_change_slow

when we start a compare for the first time, there is no changes yet in the diff tab, so we must set its title color to green

when cudatext start, the diff tab is automatically colorised as red by cudatext, so we must save the state of save of the diff tab inside the json states, so if the user already saved/synqued the changes to the original tab then we save the state of saved, and once he start writing again we save the state as unsaved,then when cudatext start we check that json state and re-apply the green or default red color again

when cudatext start ,if the diff tab is focused it gets the compare colors applied automatically, but if another tab is focused then i switch to the diff tab , the colors are not applied, it gets the colors again only when i click refresh command, fixed